title: Agent Skill Demos
description: This repo contains the files delivered by agents
url: https://git-blob.agentskill.ai
baseurl: ""

# GitHub Pages settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: true

# Default layout
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "default"

# Enable relative links for GitHub Pages
relative_links:
  enabled: true
  collections: true

# Include all markdown files
include:
  - "*.md"
  - "**/*.md"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github 